name: Start tests on pull_request
on: [push, pull_request]

jobs:
  test:
    name: Passing tests
    runs-on: ubuntu-latest
    steps:
      - name: Get repository code
        uses: actions/checkout@v3
      - name: Set node v18
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Install playwright
        run: npm i @playwright/test@latest && npx playwright install
      - name: Build
        run: npm run build
      - name: Start unit tests
        run: npm test
      - name: Start e2e tests
        run: npm run e2e